spring.application.name=springlearning

spring.data.mongodb.uri=mongodb+srv://2k23cs2314112_db_user:oSVsVIilUNXklirj@cluster0.xke73os.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=blogs
spring.data.mongodb.auto-index-creation=true
