spring.application.name=springlearning

spring.data.mongodb.uri=mongodb+srv://2k23cs2314112_db_user:oSVsVIilUNXklirj@cluster0.xke73os.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=blogs
spring.data.mongodb.auto-index-creation=true

weather.api.key=22a67c2fc78d436a9a652544261903

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=email-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sharmasuyash198@gmail.com
spring.mail.password=bvds tbzk lzzr trzy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.url=redis://default:jaSqp0P7nNwQGdht4SIYTgCl7xkDdTar@redis-18829.crce217.ap-south-1-1.ec2.cloud.redislabs.com:18829